evaluation:
    resource: "@EvaluationBundle/Resources/config/routing.yml"
    prefix:   /

tgt:
    resource: "@TgtBundle/Resources/config/routing.yml"
    prefix:   /

gth_upload:
    resource: "@GthUploadBundle/Resources/config/routing.yml"
    prefix:   /

publication:
    resource: "@PublicationBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
