<?php

namespace eventBundle\Repository;
use Doctrine\ORM\EntityRepository;
use eventBundle\Entity\Evenement;
use eventBundle\Entity\Region;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\Query;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends \Doctrine\ORM\EntityRepository
{

    public function findEntitiesByString($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p
                FROM eventBundle:Evenement p
                WHERE p.nomevent LIKE :str'
            )
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }
    public function filtreregion($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT e
                FROM eventBundle:Evenement e
                WHERE e.region =  ( select r.id from eventBundle:Region WHERE r.nom LIKE :str) '
            )
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }

}
