<?php

namespace eventBundle\Repository;
use Doctrine\ORM\EntityRepository;
use eventBundle\Entity\Region;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\Query;
/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEntitiesByString($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p
                FROM eventBundle:Region p
                WHERE p.nom LIKE :str'
            )
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }
}
