<?php

namespace TgtBundle\Repository;

/**
 * PublicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByStat()
    {
        $ql=$this->getEntityManager()
            ->createQuery("SELECT p FROM TgtBundle:publication p WHERE p.valide=:val GROUP BY p.evenement ORDER BY p.nbrVote DESC")
            ->setParameters(array('val'=>1));
        return $query= $ql->getResult();
    }
}
