<?php

namespace AchatBundle\Repository;

/**
 * LigneCommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneCommandeRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByIdPanier($id){
        $query = $this->getEntityManager()->createQueryBuilder('n')
            ->select('c')
            ->from('ecommerceBundle:LigneCommande','c')
            ->where('c.idPanier = :id')->setParameter('id',$id);
        return $query->getQuery();



        /*("SELECT c , p.image , p.description p.id FROM ecommerceBundle:LigneCommande AS c
                JOIN ecommerceBundle:Produit AS p WITH c.idproduit=p.id WHERE c.idPanier=:id")*/
    }
}
