forum_post:
    resource: "@ForumBundle/Resources/config/routing/post.yml"
    prefix:   /post/
forum_discussion:
    resource: "@ForumBundle/Resources/config/routing/discussion.yml"
    prefix:   /discussion/
forum_homepage:
    path:     /
    defaults: { _controller: ForumBundle:Default:index }
