tgt_homepageA:
    path:     /admin/welcome
    defaults: { _controller: TgtBundle:Default:index }

region_addA:
    path:     /admin/region/add
    defaults: { _controller: TgtBundle:Region:add }

region_listA:
    path:     /admin/region/list
    defaults: { _controller: TgtBundle:Region:list }

region_updateA:
    path:     /admin/region/update/{id}
    defaults: { _controller: TgtBundle:Region:update }

region_delA:
    path:     /admin/region/delete/{id}
    defaults: { _controller: TgtBundle:Region:delete }

event_addA:
    path:     /admin/evenement/add
    defaults: { _controller: TgtBundle:Event:add }

event_listA:
    path:     /admin/evenement/list
    defaults: { _controller: TgtBundle:Event:list }

event_delA:
    path:     /admin/evenement/delete/{id}
    defaults: { _controller: TgtBundle:Event:delete }

event_updateA:
    path:     /admin/evenement/update/{id}
    defaults: { _controller: TgtBundle:Event:update }

publication_listNV:
    path:     /admin/publication/listNV
    defaults: { _controller: TgtBundle:Publication:listNV }

publication_listV:
    path:     /admin/publication/listV
    defaults: { _controller: TgtBundle:Publication:list }

publication_delA:
    path:     /admin/publication/del/{id}
    defaults: { _controller: TgtBundle:Publication:delete }

publication_addA:
    path:     /admin/publication/add
    defaults: { _controller: TgtBundle:Publication:add }

publication_statRA:
    path:     /admin/publication/statistiqueR
    defaults: { _controller: TgtBundle:Publication:stat }

publication_statGA:
    path:     /admin/publication/statistiqueG
    defaults: { _controller: TgtBundle:Publication:statG }

publication_valA:
    path:     /admin/publication/val/{id}
    defaults: { _controller: TgtBundle:Publication:valide }

commentaire_listA:
    path:     /admin/listCom
    defaults: { _controller: TgtBundle:Commentaire:list }

commentaire_delA:
    path:     /admin/commentaire/del/{id}
    defaults: { _controller: TgtBundle:Commentaire:delete }

commentaire_addA:
    path:     /admin/commentaire/add
    defaults: { _controller: TgtBundle:Commentaire:add }

participant_listA:
    path:     /admin/participant/list
    defaults: { _controller: TgtBundle:User:listParticipant }

jury_listA:
    path:     /admin/jury/list
    defaults: { _controller: TgtBundle:User:listJury }

jury_newA:
    path:     /admin/jury/new/{id}
    defaults: { _controller: TgtBundle:User:newJury }

jury_moveA:
    path:     /admin/jury/move/{id}
    defaults: { _controller: TgtBundle:User:moveJury }

spectateur_listA:
    path:     /admin/spectateur/list
    defaults: { _controller: TgtBundle:User:listSpectateur }

user_delA:
    path:     /admin/user/delete
    defaults: { _controller: TgtBundle:User:delete }

user_home_pageA:
    path:     /admin/user/home
    defaults: { _controller: TgtBundle:Security:redirect }

admin_list:
    path:     /admin/admin/list
    defaults: { _controller: TgtBundle:User:listAdmin }

admin_new:
    path:     /admin/admin/new/{id}
    defaults: { _controller: TgtBundle:User:newAdmin }

admin_move:
    path:     /admin/admin/move/{id}
    defaults: { _controller: TgtBundle:User:moveAdmin }